"use client";

import type { Metadata } from "next";
import { Electrolize } from "next/font/google";
import "./globals.css";
import { Avatar, Card, Typography } from "@mui/material";
import { FaGithub, FaInstagram, FaLinkedin } from "react-icons/fa";
import { MdClose, MdMenu, MdOutlineEmail } from "react-icons/md";
import { useState } from "react";

const electrolize = Electrolize({ subsets: ["latin"], weight: "400" });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [menuOpen, setMenuOpen] = useState(false);

  const toggleMenu = () => setMenuOpen(!menuOpen);
  return (
    <html lang="en">
      <body className={electrolize.className}>
        <div className="flex flex-col h-screen">
          {/* Mobile Menu Overlay */}
          <div
            className={`fixed inset-0 bg-gray-800 bg-opacity-80 transition-transform transform ${
              menuOpen ? "translate-x-0" : "translate-x-full"
            } z-30 md:hidden`}
            style={{ transition: "transform 0.3s ease-in-out" }}
          >
            <div className="flex flex-col h-full">
              <button
                className="absolute top-5 right-5 text-gray-100 text-3xl"
                onClick={toggleMenu}
              >
                <MdClose />
              </button>
              <div className="flex flex-col items-center justify-center h-full">
                <a
                  href="/"
                  className="text-gray-100 hover:text-white text-2xl py-4"
                  onClick={toggleMenu}
                >
                  HOME
                </a>
                <a
                  href="/Posts"
                  className="text-gray-100 hover:text-white text-2xl py-4"
                  onClick={toggleMenu}
                >
                  POSTS
                </a>
                <a
                  href="/Portfolio"
                  className="text-gray-100 hover:text-white text-2xl py-4"
                  onClick={toggleMenu}
                >
                  PORTFOLIO
                </a>
                <a
                  href="/About"
                  className="text-gray-100 hover:text-white text-2xl py-4"
                  onClick={toggleMenu}
                >
                  ABOUT
                </a>
                <a
                  href="/Gallery"
                  className="text-gray-100 hover:text-white text-2xl py-4"
                  onClick={toggleMenu}
                >
                  GALLERY
                </a>
                <a
                  href="#"
                  className="text-gray-100 hover:text-white text-2xl py-4"
                  onClick={toggleMenu}
                >
                  CONTACT
                </a>
              </div>
            </div>
          </div>

          {/* Main Content */}
          <div className="flex flex-1 flex-col md:flex-row">
            {/* Sidebar */}
            <div>
              <div className="flex flex-col items-center justify-center text-center w-full h-full p-5 md:fixed relative md:w-[30rem] md:border-r md:border-slate-800 md:z-50 my-10 md:my-0 bg-black border-0">
                <div className="grid place-items-center gap-5">
                  <Avatar
                    alt="Oka Sentana"
                    src="/static/images/avatar/1.jpg"
                    sx={{ width: 100, height: 100 }}
                  />
                  <h1 className="text-2xl md:text-4xl">I'M OKA SENTANA</h1>
                  <h2 className="text-md md:text-lg">Call me Oka</h2>

                  <div className="flex items-center justify-center gap-4">
                    <a href="#" aria-label="LinkedIn">
                      <FaLinkedin className="text-3xl md:text-4xl" />
                    </a>
                    <a href="#" aria-label="GitHub">
                      <FaGithub className="text-3xl md:text-4xl" />
                    </a>
                    <a href="#" aria-label="Instagram">
                      <FaInstagram className="text-3xl md:text-4xl" />
                    </a>
                    <a href="#" aria-label="Email">
                      <MdOutlineEmail className="text-3xl md:text-4xl" />
                    </a>
                  </div>
                </div>
                <div className="text-center p-5 w-full md:absolute md:bottom-0 ">
                  <span className="text-gray-100">
                    © Oka Sentana 2024 • imprint
                  </span>
                </div>
              </div>
            </div>

            {/* Content Area */}
            <div className="flex-1">
              {/* Sticky Header */}
              <nav className="flex items-end justify-between p-5 md:p-8 fixed top-0 w-full  z-20 border-b border-slate-800 md:sticky md:w-auto md:top-0 bg-black">
                {/* Hamburger Menu for Mobile */}
                <button
                  className="text-gray-400 hover:text-white md:hidden transition"
                  onClick={toggleMenu}
                >
                  {menuOpen ? (
                    <MdClose className="text-3xl" />
                  ) : (
                    <MdMenu className="text-3xl" />
                  )}
                </button>

                {/* Desktop Menu */}
                <div className="hidden md:flex gap-8 md:items-end md:absolute md:right-0 md:top-0 md:mt-5 md:mx-5">
                  <a href="/" className="text-gray-100 hover:text-white">
                    HOME
                  </a>
                  <a href="/Posts" className="text-gray-100 hover:text-white">
                    POSTS
                  </a>
                  <a
                    href="/Portfolio"
                    className="text-gray-100 hover:text-white"
                  >
                    PORTFOLIO
                  </a>
                  <a href="/About" className="text-gray-100 hover:text-white">
                    ABOUT
                  </a>
                  <a href="/Gallery" className="text-gray-100 hover:text-white">
                    GALLERY
                  </a>
                  <a href="#" className="text-gray-100 hover:text-white">
                    CONTACT
                  </a>
                </div>
              </nav>

              {/* Children Content */}
              <main className=" md:ml-[30rem] ml-0 p-5">{children}</main>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
