import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Avatar, Card, Typography } from "@mui/material";
import { FaGithub, FaInstagram, FaLinkedin } from "react-icons/fa";
import { MdOutlineEmail } from "react-icons/md";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen">
          {/* Sidebar */}
          <div className="h-full w-1/3 rounded-none border-r border-gray-800">
            <div className="flex flex-col items-center justify-center text-center w-full h-screen">
              <div className=" grid place-items-center gap-5">
                <Avatar
                  alt="Remy Sharp"
                  src="/static/images/avatar/1.jpg"
                  sx={{ width: 100, height: 100 }}
                />
                <h1 className="text-4xl">I'M OKA SENTANA</h1>
                <h2>Call me Oka</h2>

                <div className=" flex items-center justify-center gap-5">
                  <a href="#" aria-label="LinkedIn">
                    <FaLinkedin className=" text-4xl" />
                  </a>
                  <a href="#" aria-label="GitHub">
                    <FaGithub className=" text-4xl" />
                  </a>
                  <a href="#" aria-label="Instagram">
                    <FaInstagram className=" text-4xl" />
                  </a>
                  <a href="#" aria-label="Email">
                    <MdOutlineEmail className=" text-4xl" />
                  </a>
                </div>
              </div>
              <div className="text-center p-5 w-full absolute bottom-0">
                <span>© Oka Sentana 2024 • imprint</span>
              </div>
            </div>
          </div>

          {/* Main Content */}
          <div className="ml-1/4 flex-1 overflow-auto">
            {/* Sticky Header */}
            <nav className="flex space-x-4 mb-8 border-b border-gray-700 p-5 sticky top-0 bg-gray-900 z-10">
              <a href="#" className="text-gray-400 hover:text-white transition">
                HOME
              </a>
              <a href="#" className="text-gray-400 hover:text-white transition">
                POSTS
              </a>
              <a href="#" className="text-gray-400 hover:text-white transition">
                PORTFOLIO
              </a>
              <a href="#" className="text-gray-400 hover:text-white transition">
                ABOUT
              </a>
              <a href="#" className="text-gray-400 hover:text-white transition">
                ACCOMPLISHMENTS
              </a>
              <a href="#" className="text-gray-400 hover:text-white transition">
                CONTACT
              </a>
              <div className="ml-auto flex items-center space-x-4">
                <button className="text-gray-400 hover:text-white transition">
                  EN
                </button>
                <button className="text-gray-400 hover:text-white transition">
                  🌙
                </button>
              </div>
            </nav>

            {/* Children Content */}
            <main className="space-y-8 p-5">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
